### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [adkoge/firehose#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by adkoge** [comment]
I noticed that yesterday after submitting.

I went back and added in the viewport meta tag to my head.
![2016-01-12 13_41_08-c__users_adkog_desktop_vagrant_src_splurty_app_views_layouts_application html er](https://cloud.githubusercontent.com/assets/11382300/12273144/38b73436-b932-11e5-836e-fa44aff81f59.png)

**Comment by kenmazaika** [comment]
:+1: Thumbs up!  Looks perfect!
